
export const ENGINEERING_SYNONYMS: Record<string, string[]> = {
  javascript: ['js', 'ecmascript', 'es6', 'es2015', 'es2020'],
  typescript: ['ts', 'typed javascript'],
  'node.js': ['nodejs', 'node', 'express.js', 'expressjs'],
  react: ['reactjs', 'react.js', 'react hooks', 'jsx'],
  vue: ['vuejs', 'vue.js', 'vue 3'],
  angular: ['angularjs', 'angular 2+'],
  'next.js': ['nextjs', 'next js'],
  python: ['py', 'python3', 'python 3'],
  java: ['spring', 'spring boot', 'jvm', 'maven', 'gradle'],
  'c#': ['csharp', 'dotnet', '.net', 'asp.net'],
  'c++': ['cpp', 'c plus plus'],
  golang: ['go', 'go lang'],
  rust: ['rust lang'],
  ruby: ['ruby on rails', 'rails', 'ror'],
  php: ['laravel', 'symfony', 'wordpress'],
  postgresql: ['postgres', 'psql', 'pg'],
  mysql: ['my sql', 'mariadb'],
  mongodb: ['mongo', 'document database'],
  redis: ['redis cache', 'in-memory cache'],
  elasticsearch: ['elastic search', 'elk stack', 'opensearch'],
  aws: ['amazon web services', 'amazon aws', 'ec2', 's3', 'lambda'],
  gcp: ['google cloud', 'google cloud platform', 'bigquery', 'gke'],
  azure: ['microsoft azure', 'azure devops', 'azure functions'],
  terraform: ['infrastructure as code', 'iac', 'pulumi'],
  graphql: ['graph ql', 'graph-ql', 'apollo'],
  kafka: ['apache kafka', 'event streaming', 'message queue'],
  rabbitmq: ['message broker', 'amqp'],
  webpack: ['bundler', 'vite', 'esbuild', 'rollup'],
  tailwind: ['tailwindcss', 'tailwind css'],
  'react native': ['rn', 'cross-platform mobile'],
  flutter: ['dart', 'cross-platform mobile'],
  swift: ['ios development', 'xcode'],
  kotlin: ['android development', 'android studio'],
};


